### ISSUE TITLE
A function cannot be assigned on the Henkan/Muhenkan key

### ISSUE THREAD

**Issue by YoshitoOhta** [ueno/libskk#38]
The Henkan/Muhenkan key doesn't work and they cannot be assigned any functions.
I made a new keymap rule like a below file.

file: hiragana.json
{
    "include": [
        "default"
    ],
     "define": {
        "keymap": {
            "Q": "start-preedit",      <- Works fine
            "C-j": "commit",            <- Works fine
            "Henkan": "start-preedit",  <- Don't work
            "Muhenkan": "commit"      <- Don't work
        }
}

It seems that the Henkan / Muhenkan key are processed as a right / left Shift key in the 'key-event.vala'. Is this right?

```
    static const NameKeyvalEntry[] NAME_KEYVALS = {
        { Keysyms.Up, "Up" },
        { Keysyms.Down, "Down" },
        { Keysyms.Left, "Left" },
        { Keysyms.Right, "Right" },
        { Keysyms.Page_Up, "Page_Up" },
        { Keysyms.KP_Page_Up, "Page_Up" },
        { Keysyms.Page_Down, "Page_Down" },
        { Keysyms.KP_Page_Down, "Page_Down" },
        { Keysyms.Muhenkan, "lshift" },                       <--
        { Keysyms.Henkan, "rshift" }                          <--
    };
```

Sorry, Below text is in Japanese.

変換キーと無変換キーに機能を割つけるルールを作成したが機能しない様です。
key-event.valaを見ると強制的にシフトキーとして処理しようとしている様に見えます。
この理解で正しいでしょうか？
また、変換/無変換キーに機能を割りつける方法はruleの作成以外にありますか？

**Comment by ueno** [comment]
This should be fixed as part of #54.
