### ISSUE TITLE
Hitting Shift while converting confirms current choice

### ISSUE THREAD

**Issue by uKLEina** [ueno/libskk#55]
# Environment
- Debian Buster
- ibus 1.5.18
- ibus-skk 1.4.2
- libskk 1.0.4

also reproduced with fcitx 4.2.9.6 and fcitx-skk 0.1.4

# Steps to reproduce
1. Start input with Shift.
1. Hit Space to start converting
1. Hit Shift

# Expected Result
Nothing happens. 

# Actual Result
The current selection is confirmed.

# Notes
I use xcape for enabling SandS feature, and it sends Shift + Space when you hit space key once. So with current behavior, I can only select 1st candidate of converting. Also, in ddskk, hitting Shift while converting does nothing, so current behavior does not match with ddskk.
This happens after I updated libskk from 1.0.3 to 1.0.4, so I think libskk 1.0.4 causes this problem.

Edit: I tested with libskk 1.0.3 and this issue doesn't happen, so I think it's confirmed that libskk 1.0.4 causes this behavior.

**Comment by ueno** [comment]
I'm guessing you are using the latest Debian package of libskk, which accidentally included the patch not merged in upstream:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903159#20

The similar symptoms were already reported in the review:
https://github.com/ueno/libskk/pull/54#issuecomment-404041744

**Comment by ueno** [comment]
cc @hosiet

**Comment by hosiet** [comment]
Ack. Will revert the unmerged patch if I could confirm the bug.

**Comment by ueno** [comment]
Closing, as the new package has been submitted:
https://metadata.ftp-master.debian.org/changelogs/main/libs/libskk/libskk_1.0.4-2_changelog
