### ISSUE TITLE
rule for converting hiragana to kanji

### ISSUE THREAD

**Issue by loretoparisi** [ueno/libskk#65]
I have this kanji  `退屈であくびばっかしていた毎日` text. I have inverted to Hiragana using kakasi like

```
echo "退屈であくびばっかしていた毎日" | kakasi -JH -iutf8 -outf8
たいくつであくびばっかしていたまいにち
```

Now I want to invert this doing the opposite with `libskk`, but I get no output.

```
ip-192-168-22-127:libskk loretoparisi$ echo "たいくつ であくびばっかしていた まいにち" | skk -f /Users/loretoparisi/Documents/Projects/AI/dict/SKK-JISYO.L
{ "input": "たいくつ であくびばっかしていた まいにち", "output": "", "preedit": "" }
```

I was able to do this using the web service called `mecab-skkserve` [here](http://anti.rosx.net/etc/tools/rome.php), so I assume I'm using the wrong command or dictionaries.
Any hint?

Thank you in advance.

**Comment by ueno** [comment]
I would suggest to read the [official document](http://openlab.jp/skk/doc.html) explaining SKK, before asking such questions.  Although it's only in Japanese, I guess you could use a machine translation service.

In short, it's not how SKK works; it's an input method, not a text processing tool.

**Comment by loretoparisi** [comment]
@ueno yes the problem is that the docs it's not in english and it's pretty hard to understand how SKK works. Thank you for your help by the way.

I'm using **kakasi** as `"kanji kana simple inverter`, as it stated inhttp://kakasi.namazu.org/index.html.en and _I would like_ to use **SKK** as `simple kana kanji converter` in the way the mecab-skkserve does.

Thanks again, maybe I will found some help in SF.
