### ISSUE TITLE
linux: error while loading shared libraries: libskk.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by loretoparisi** [ueno/libskk#66]
Hello, I have built a `Dockerfile` to simplify the install on `linux`. Everything works, but when running I get an error: 

```
$ skk
skk: error while loading shared libraries: libskk.so.0: cannot open shared object file: No such file or directory
```

My Dockerfile is [here](https://github.com/loretoparisi/docker/blob/master/libskk/Dockerfile).

**Comment by ueno** [comment]
`man ldconfig`.

Why don't you use the `libskk-dev` package from the Ubuntu repo?

**Comment by loretoparisi** [comment]
@ueno thanks forget about it. Just added to `ldconfig` and it worked. I prefer to build from scrach, thank you.
